<div class="navbar navbar-dark navbar-expand-lg leading-navigation">

  <div class="panel-toggler p-1">
    <span class="navbar-toggler-icon"></span>
  </div>


  <ul class="navbar-nav ml-5">
    <li class="nav-item"><a class="nav-link" href="">Dashboard</a></li>
    <li class="nav-item"><a class="nav-link" href="">Edit Post</a></li>
    <li class="nav-item"><a class="nav-link" href="">New</a></li>
  </ul>

</div>
