<div class="navbar navbar-dark navbar-expand-lg justify-content-between leading-navigation">

  <div class="panel-toggler p-1">
    <span class="navbar-toggler-icon"></span>
  </div>


  <ul class="navbar-nav ml-5">
    <li class="nav-item"><a class="nav-link" href="">Dashboard</a></li>
    <li class="nav-item"><a class="nav-link" href="">Edit Post</a></li>
    <li class="nav-item"><a class="nav-link" href="">New</a></li>
  </ul>

  <ul class="navbar-nav navbar-right">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="">Dawood Najam</a>
      <ul class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" href="">Dropdown Item 1</a>
        <a class="dropdown-item" href="">Dropdown Item 1</a>
        <a class="dropdown-item" href="">Dropdown Item 1</a>
        <a class="dropdown-item" href="">Dropdown Item 1</a>
      </ul>
    </li>
  </ul>


</div>
